export const SIDEBAR_NAV_ITEMS = [
  { to: '/', label: '首页' },
  { to: '/chat', label: '智能对话' },
  { to: '/translation-search', label: '翻译与深搜' },
  { to: '/listening', label: '听力练习' },
  { to: '/reading', label: '阅读练习' },
  { to: '/writing', label: '写作练习' },
  { to: '/speaking', label: '口语练习' },
  { to: '/vocabulary', label: '词汇学习' },
  { to: '/reports', label: '学习报告' },
  { to: '/plans', label: '个性化计划' },
  { to: '/reminders', label: '提醒中心' },
  { to: '/achievements', label: '成就中心' },
  { to: '/community', label: '学习社区' },
  { to: '/groups', label: '学习小组' },
  { to: '/payment', label: '支付中心' },
  { to: '/admin', label: '运营后台' },
  { to: '/campaigns', label: '活动中心' },
];
